### ISSUE TITLE
test_queue_size dequeueing fails

### ISSUE THREAD

**Issue by eccabay** [Buntry/swdev20_a1p2#4]
In your test_queue_size method, your dequeue size asserts are off by one. When you enqueue, you add 100 elements (since you iterate up to 99, check that the size is equal and then add another element to make the queue of length 100) and then starting at 100 assert that the length is 99, which is incorrect. Can you update this test so that it will pass? (Either assert that size == i or dequeue before asserting size equals) Thanks!

**Comment by Buntry** [comment]
I will inspect this issue and report back soon.

**Comment by Buntry** [comment]
this change has been merged. feel free to close this whenever you feel the issue has been resolved
