### ISSUE TITLE
StrQueue should inherit from Queue

### ISSUE THREAD

**Issue by eccabay** [Buntry/swdev20_a1p2#5]
You currently have StrQueue inherit from Object, but it would greatly minimize code duplication to inherit from Queue instead (especially methods like length and is_empty where nothing needs to change at all between implementations). Please change this so we don't have to rewrite all the same code again... :( 
Thanks!

**Comment by Buntry** [comment]
Why should you be allowed to do enqueue Object* on a StrQueue. Doesn't sound right to me.
If you care a lot about reducing the amount of code, you could use composition to implement StrQueue.

**Comment by eccabay** [comment]
What are you talking about? Having StrQueue be a child class of Queue would not mean you could call StrQueue->enqueue(Object). In fact, doing so will mean your code does not even compile.

**Comment by Buntry** [comment]
What follows should not be possible.
```
StrQueue* sq = new StrQueue();
sq->enqueue(new Object());
```

**Comment by Buntry** [comment]
As it stands, this is not possible. If you want to make StrQueue a subclass of Queue, this would be a valid method call on StrQueue. If you want to reuse your Queue class, please do so using composition. I cannot help you further unless you made an extraordinary argument why this is bad.

Again, I'm not saying you cannot use subclasses for your implementation, but you should be aware of the risks of allowing them.

**Comment by eccabay** [comment]
I don't know why you're saying having StrQueue inherit from Queue would make 
```
StrQueue* sq = new StrQueue();
sq->enqueue(new Object());
```
a valid code snippet. This is not the case at all. I took the liberty of adjusting the spec to inherit from Queue for testing purposes, and attempting to enqueue a new Object to a StrQueue resulted in a compile error, as you can see in the attached photo.
![Screenshot from 2020-01-30 07-25-24](https://user-images.githubusercontent.com/60074782/73450088-a2625300-4332-11ea-902a-7d7c7c95ec60.png)

**Comment by Buntry** [comment]
Fair, this will not compile. However, I am not saying that you are unable to subclass in your implementation. I am saying that I will not enforce that in the spec. You can successfully pass all tests if you choose to subclass or if you don't.

**Comment by Buntry** [comment]
I am leaving your decision to subclass up to your implementation.

**Comment by Buntry** [comment]
I've linked a piazza thread that mentions the consequences of overloading your methods.

In this case, you would use the original Queue for logic and casting it back to a String for a valid return type. I'm not preventing this, but I highly suggest against it.

https://piazza.com/class/k51bluky59n2jr?cid=331
